version: '3.8'
services:
  m81-api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: m81-api
    entrypoint: sh -c "yarn install --frozen-lockfile && yarn start:dev"
    environment:
      - POSTGRES_HOST=m81-db
    env_file:
      - .env
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - ${PORT}:${PORT}
    networks:
      - m81-net
    depends_on:
      - m81-db

  m81-db:
    image: mongo:latest
    container_name: m81-db
    environment:
      MONGODB_URI: ${MONGODB_URI}
    volumes:
      - data:/data/db
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    networks:
      - m81-net
      
volumes:
  data:

networks:
  m81-net: